language: erlang
before_script: "make get-lfetool"
script: "make check"
notifications:
  irc: "irc.freenode.org#cogitat"
  recipients:
    - duncan@cogitat.io
otp_release:
  - 17.0
  - R16B03
  - R15B03
